### ISSUE TITLE
Öneriler

### ISSUE THREAD

**Issue by c0b41** [erayarslan/singlepage.ninja#1]
Addy Osmani'nin Developing Backbone.js Applications örnek alınabilir.

Biz zamanında çevirmeye girişmiştik öylee kaldı. 

https://github.com/enverarslan/backbone-temelleri/tree/develop

**Comment by erayarslan** [comment]
Benim de aklıma direk backbone-fundamentals geldi.
Dokümanı oluşturmak içinde GitHub üzerinden izleyeceğim adım böyle olacak.
Çünkü birikimimi aktarmakta sıkıntı yaşacağımı düşünüyorum.
İnsanların katkılarına baya bi ihtiyacım var.
Özellikle anlatış tarzıma.

Bi de AngularJS tarafında baya bi eksiğim var.
Backbone.js dışında AngularJS ile de, geliştirilecek uygulama için bi alternatif oluşturulabilir.

**Comment by ayhankuru** [comment]
@erayarslan todomvc örnekleri üzerinden farklı spa frameworklerine göre anlatabilirsin.İlk olarak yazmaya başladıktan sonra olduğu gib ilerlemek gerekiyor yoksa bi noktadan sonra sıkıcı gelecektir sen her zamanki tarzında yaz :smile:

**Comment by erayarslan** [comment]
sade bi şekilde ilerliycem zaten.
işte kullanılacak teknolojilerin ne/ne değil olduğu.
servis geliştirilmesi.
örnek bi single-page uygulama geliştirilmesi (muhtemelen blo
single-page uygulamalarda # in kaldırılması ve mantığı.
ve temiz bi şekilde seo ayarlamaları google a indexletilmesi.

single-page uygulama geliştirilirken de yeoman ya da backbone-boilerplate gibi
hazır skeleton projelerle değil de kendi yapımızı oluşturarak geliştircem.
çünkü her satırın niye olduğunun anlaşılması gerekiyor.

yani öyle düşündüm :smile:

**Comment by ozziest** [comment]
2 adet sorum var Eray, cevap bekleyen. 

- Doküman olacak mı?
- En alt seviye ne olacak? Sadece jQuery bilen geliştiricilere göre mi hazırlanacak? Yoksa daha yukarısı mı?

**Comment by erayarslan** [comment]
Dokümandan kastı anlamadım ama her şeyi anlatarak bir uygulama geliştirilecek.
Ne bileyim Backbone.Model kullanılacaksa projenin bi yerinde. Model anlatılacak örnekler gösterilecek. Ve uygulamadaki kısmı da yazılacak, gösterilecek.

Bu yüzden en alt seviye JavaScript'i basit kullanabilen biri seviyesinde olacaktır.

**Comment by ozziest** [comment]
Eray bence sen bir örnek ile başla, üzerinde tartışalım. Şuan çok havada kalıyor gibi.

**Comment by erayarslan** [comment]
Servisiyle başladım işte :smile:
