### ISSUE TITLE
apiDoc Kullanımı

### ISSUE THREAD

**Issue by ozziest** [erayarslan/singlepage.ninja#2]
Back-end bölümünün dokümantasyonunun otomatik oluşturulabilmesi için [apidocjs](http://apidocjs.com/) aracından yararlanılabilir. İlk etapta bunun denemesi yapılıp, açıklama bloklarının nereye (tahminimce rotaların tanımlandığı bölümler üzerine) konulacağı belirlenmeli. Böylece herkes API'ın nasıl çalışacağını kolayca anlayabilir.

**Comment by erayarslan** [comment]
Komplike bi API olmayacak.

Post üzerine CRUD olacak sadece. (Blog)
Ve basit Token-Security.
Sade yorum satırlarıyla bunlar anlatılabilir.

Yine de README.md içerisinde detaylandırabilirim.

**Comment by ozziest** [comment]
Eğer komple bir projenin nasıl yapılabileceğini anlatacaksak basit bile olsa bir API dokümanı olmalı. Bir pull-request gönderebilirim ya da benim formladığım repoya bakabilirsin.

**Comment by erayarslan** [comment]
@ozziest seni collaborator olarak ekledim.
Döküman kısmında yardımcı olursan sevinirim :smile:

**Comment by ozziest** [comment]
Bana böyle şeylerle gel. :+1:
